/**
 * Cross-browser check for the PNG export.
 *
 * The export is browser code, so it is exercised in a browser rather than in
 * Node: `src/exportImage.ts` is bundled on its own (no app, no dev server) and
 * served over http, so the page has a real origin and `URL.createObjectURL` and
 * canvas readback behave the way they do in production.
 *
 * The assertions look at pixels, not at the shape of the SVG string. A failed
 * rasterization is not an exception in WebKit, it is a blank bitmap, and that is
 * exactly what a signature/dimension check cannot see.
 */
import { chromium, firefox, webkit, type BrowserType } from "playwright";
import { build } from "vite";
import { createServer, type Server } from "node:http";
import { AddressInfo } from "node:net";
import path from "node:path";

const BACKGROUND = [239, 239, 239]; // the #efefef page fill
const FRAME = 56; // inside the 64px page margin, with slack for antialiasing
const CHANNEL_TOLERANCE = 12;
// Table cells are painted white over the page colour, so "not the background"
// only tells us something was drawn. Dark pixels are the text, and that is what
// tells us the export is readable rather than an empty grid.
const MIN_PAINTED = 0.005;
const MIN_TEXT = 0.002;
const MAX_TEXT = 0.4;
const MAX_TEXT_SPREAD = 0.05; // engines pick different fonts; shapes still agree
const DARK_LUMINANCE = 128;

const labels = {
  questionLabel: "Question:", variantLabel: "Variant:", codeLabel: "This is the code:",
  resultLabel: "... and this is the result:", viewCodeLabel: "View", viewResultLabel: "View result",
  matchesLabel: "matches", doesNotMatchLabel: "does not match",
  generatedByLabel: "Generated by SQL Validator at test time",
};

const cells = (columns: number, rows: number) => Array.from({ length: rows }, (_, row) =>
  Array.from({ length: columns }, (_, column) =>
    column === 0 ? null : column === 1 ? Array.from(new Uint8Array([0, row % 256, 255])) : `<value ${row}-${column}>`));

const fixtures = {
  // Wide enough to exercise the grow-and-truncate path and a tall canvas.
  wideQuery: {
    labels,
    query: {
      question: { category: { display_number: "82" }, display_sequence: "D", description: "Render a large escaped result consistently across browser engines" },
      code: "SELECT p.name, COUNT(o.id) AS orders FROM Person p LEFT JOIN Orders o ON o.person_id = p.id WHERE p.name < 'Z' GROUP BY p.name ORDER BY p.name;",
      result: { columns: Array.from({ length: 48 }, (_, index) => index % 2 ? "label" : `column_${index}`), data: cells(48, 90) },
      isCorrect: true,
    },
  },
  narrowQuery: {
    labels,
    query: {
      question: { category: { display_number: "3" }, display_sequence: "A", description: "A short question with an <escaped> & typographic title" },
      code: "SELECT id, name FROM Person ORDER BY name;",
      result: { columns: ["id", "name"], data: [[1, "Alice & Bob"], [2, null]] },
      isCorrect: false,
    },
  },
  view: {
    labels,
    view: { view: { name: "people_view", query: "SELECT id, name FROM Person WHERE name IS NOT NULL" }, result: { columns: ["id", "name"], data: [[1, "Ada"], [2, "Grace"]] } },
  },
};

interface Engine {
  name: string;
  type: BrowserType;
  /** `args` is a Chromium option. WebKit exits immediately when handed one. */
  args: string[];
}

const ENGINES: Engine[] = [
  { name: "chromium", type: chromium, args: ["--no-sandbox"] },
  { name: "firefox", type: firefox, args: [] },
  { name: "webkit", type: webkit, args: [] },
];

interface Measurement {
  svgHash: number;
  svgLength: number;
  renderedWidth: number;
  renderedHeight: number;
  pngWidth: number;
  pngHeight: number;
  isPng: boolean;
  byteLength: number;
  repeatMatches: boolean;
  minAlpha: number;
  paintedRatio: number;
  textRatio: number;
  framePixelsOutsideBackground: number;
}

/** Bundle just the export module for the browser: no app entry, no dev server. */
async function bundleExportModule(): Promise<string> {
  const result = await build({
    configFile: false,
    logLevel: "error",
    build: {
      write: false,
      minify: false,
      lib: { entry: path.resolve("src/exportImage.ts"), name: "ExportImage", formats: ["iife"], fileName: () => "export-image.js" },
    },
  });
  const outputs = (Array.isArray(result) ? result : [result]) as Array<{ output?: Array<{ type: string; code?: string }> }>;
  const chunk = outputs.flatMap(entry => entry.output ?? []).find(item => item.type === "chunk" && item.code);
  if (!chunk?.code) throw new Error("Failed to bundle src/exportImage.ts for the browser");
  return chunk.code;
}

function serve(bundle: string): Promise<{ url: string; close: () => Promise<void> }> {
  const server: Server = createServer((request, response) => {
    if (request.url === "/export-image.js") {
      response.writeHead(200, { "content-type": "text/javascript; charset=utf-8" }).end(bundle);
      return;
    }
    response.writeHead(200, { "content-type": "text/html; charset=utf-8" })
      .end("<!doctype html><meta charset=\"utf-8\"><title>export</title><script src=\"/export-image.js\"></script>");
  });
  return new Promise(resolve => server.listen(0, "127.0.0.1", () => {
    const { port } = server.address() as AddressInfo;
    resolve({
      url: `http://127.0.0.1:${port}/`,
      close: () => new Promise<void>((done, fail) => server.close(error => error ? fail(error) : done())),
    });
  }));
}

interface PageInput {
  input: unknown;
  background: number[];
  tolerance: number;
  frame: number;
  darkLuminance: number;
}

/** Runs in the browser: render, rasterize through the production path, read pixels back. */
/* eslint-disable @typescript-eslint/no-explicit-any */
async function measureInPage({ input, background, tolerance, frame, darkLuminance }: PageInput): Promise<Measurement> {
  const api = (globalThis as any).ExportImage;
  const revive = (value: any): any => Array.isArray(value) && value.every((item: any) => typeof item === "number")
    ? new Uint8Array(value)
    : value;
  const payload = JSON.parse(JSON.stringify(input), (_key, value) => revive(value));
  payload.labels.truncatedLabel = ({ rows, totalRows, columns, totalColumns }: Record<string, number>) =>
    `Showing ${rows} of ${totalRows} rows and ${columns} of ${totalColumns} columns`;

  const rendered = api.renderExportSvg(payload);
  let svgHash = 2166136261;
  for (let index = 0; index < rendered.svg.length; index++) {
    svgHash = Math.imul(svgHash ^ rendered.svg.charCodeAt(index), 16777619) >>> 0;
  }

  const blob = await api.rasterizeExportPng(rendered);
  const bytes = new Uint8Array(await blob.arrayBuffer());
  const repeat = new Uint8Array(await (await api.rasterizeExportPng(rendered)).arrayBuffer());

  const bitmap = await createImageBitmap(blob);
  const canvas = document.createElement("canvas");
  canvas.width = bitmap.width;
  canvas.height = bitmap.height;
  const context = canvas.getContext("2d", { willReadFrequently: true });
  if (!context) throw new Error("Canvas rendering is unavailable");
  context.drawImage(bitmap, 0, 0);
  const { data } = context.getImageData(0, 0, canvas.width, canvas.height);

  const isBackground = (offset: number) => background.every((channel, index) => Math.abs(data[offset + index] - channel) <= tolerance);

  let painted = 0;
  let text = 0;
  let minAlpha = 255;
  let framePixelsOutsideBackground = 0;
  for (let y = 0; y < canvas.height; y++) {
    const inVerticalFrame = y < frame || y >= canvas.height - frame;
    for (let x = 0; x < canvas.width; x++) {
      const offset = (y * canvas.width + x) * 4;
      if (data[offset + 3] < minAlpha) minAlpha = data[offset + 3];
      if (0.299 * data[offset] + 0.587 * data[offset + 1] + 0.114 * data[offset + 2] < darkLuminance) text++;
      if (isBackground(offset)) continue;
      painted++;
      if (inVerticalFrame || x < frame || x >= canvas.width - frame) framePixelsOutsideBackground++;
    }
  }

  return {
    svgHash,
    svgLength: rendered.svg.length,
    renderedWidth: rendered.width,
    renderedHeight: rendered.height,
    pngWidth: bitmap.width,
    pngHeight: bitmap.height,
    isPng: bytes[0] === 0x89 && bytes[1] === 0x50 && bytes[2] === 0x4e && bytes[3] === 0x47,
    byteLength: bytes.byteLength,
    repeatMatches: repeat.byteLength === bytes.byteLength && bytes.every((value, index) => value === repeat[index]),
    minAlpha,
    paintedRatio: painted / (canvas.width * canvas.height),
    textRatio: text / (canvas.width * canvas.height),
    framePixelsOutsideBackground,
  };
}
/* eslint-enable @typescript-eslint/no-explicit-any */

function check(name: string, fixture: string, measurement: Measurement, failures: string[]): void {
  const fail = (message: string) => failures.push(`[${name}/${fixture}] ${message}`);
  if (!measurement.isPng) fail("output is not a PNG");
  if (measurement.byteLength < 1024) fail(`PNG is implausibly small (${measurement.byteLength} bytes)`);
  if (measurement.pngWidth !== measurement.renderedWidth || measurement.pngHeight !== measurement.renderedHeight) {
    fail(`PNG is ${measurement.pngWidth}x${measurement.pngHeight}, expected ${measurement.renderedWidth}x${measurement.renderedHeight}`);
  }
  if (measurement.minAlpha !== 255) fail(`PNG has transparent pixels (min alpha ${measurement.minAlpha}); the SVG did not rasterize`);
  // A blank bitmap is the failure mode a signature check misses.
  if (measurement.paintedRatio < MIN_PAINTED) fail(`PNG is effectively blank (painted ratio ${measurement.paintedRatio.toFixed(4)})`);
  if (measurement.textRatio < MIN_TEXT) fail(`PNG has no legible text (text ratio ${measurement.textRatio.toFixed(4)}); the fonts or the glyphs did not render`);
  if (measurement.textRatio > MAX_TEXT) fail(`PNG is mostly dark (text ratio ${measurement.textRatio.toFixed(4)}); layout is probably wrong`);
  // Content in the page margin means something overflowed and is being clipped.
  if (measurement.framePixelsOutsideBackground > 0) fail(`${measurement.framePixelsOutsideBackground} px of content sit in the ${FRAME}px page margin; the layout overflows the canvas`);
  if (!measurement.repeatMatches) fail("two rasterizations of the same SVG produced different PNGs");
}

async function run(engine: Engine, url: string, allowSkip: boolean): Promise<Record<string, Measurement> | null> {
  const { name, type, args } = engine;
  let browser;
  try {
    browser = await type.launch({ headless: true, args });
  } catch (error) {
    if (!allowSkip) throw new Error(`[${name}] failed to launch: ${String(error).split("\n")[0]}`);
    console.warn(`[${name}] skipped: failed to launch (${String(error).split("\n")[0]})`);
    return null;
  }
  try {
    const page = await browser.newPage();
    // tsx strips types with esbuild, which emits a `__name` helper call around
    // the page function. Playwright ships that function to the browser as
    // source, so the helper has to exist there too.
    await page.addInitScript({ content: "globalThis.__name = globalThis.__name || (fn => fn);" });
    page.on("pageerror", error => console.error(`[${name}] page error: ${error.message}`));
    await page.goto(url, { waitUntil: "load" });
    const measurements: Record<string, Measurement> = {};
    for (const [fixture, input] of Object.entries(fixtures)) {
      measurements[fixture] = await page.evaluate(measureInPage, { input, background: BACKGROUND, tolerance: CHANNEL_TOLERANCE, frame: FRAME, darkLuminance: DARK_LUMINANCE });
    }
    return measurements;
  } finally {
    await browser.close();
  }
}

async function main(): Promise<void> {
  const allowSkip = !process.env.CI;
  const server = await serve(await bundleExportModule());
  const failures: string[] = [];
  const collected: Array<[string, Record<string, Measurement>]> = [];
  try {
    for (const engine of ENGINES) {
      const { name } = engine;
      const measurements = await run(engine, server.url, allowSkip);
      if (!measurements) continue;
      collected.push([name, measurements]);
      for (const [fixture, measurement] of Object.entries(measurements)) {
        check(name, fixture, measurement, failures);
        console.log(`[${name}/${fixture}] ${measurement.pngWidth}x${measurement.pngHeight}, ${(measurement.byteLength / 1024).toFixed(0)} KiB, painted ${(measurement.paintedRatio * 100).toFixed(1)}%, text ${(measurement.textRatio * 100).toFixed(2)}%`);
      }
    }
  } finally {
    await server.close();
  }

  if (collected.length === 0) throw new Error("No browser engine was available; the export was not verified");

  // renderExportSvg is pure, so every engine must produce the same SVG and the
  // same canvas size. Only the rasterized ink may differ, and only a little.
  for (const fixture of Object.keys(fixtures)) {
    const perEngine = collected.map(([name, measurements]) => [name, measurements[fixture]] as const);
    const [, reference] = perEngine[0];
    for (const [name, measurement] of perEngine.slice(1)) {
      if (measurement.svgHash !== reference.svgHash || measurement.svgLength !== reference.svgLength) {
        failures.push(`[${name}/${fixture}] rendered a different SVG than ${perEngine[0][0]} (${measurement.svgLength} vs ${reference.svgLength} chars)`);
      }
      if (measurement.pngWidth !== reference.pngWidth || measurement.pngHeight !== reference.pngHeight) {
        failures.push(`[${name}/${fixture}] PNG is ${measurement.pngWidth}x${measurement.pngHeight}, ${perEngine[0][0]} produced ${reference.pngWidth}x${reference.pngHeight}`);
      }
    }
    const ratios = perEngine.map(([, measurement]) => measurement.textRatio);
    const spread = Math.max(...ratios) - Math.min(...ratios);
    if (spread > MAX_TEXT_SPREAD) {
      failures.push(`[${fixture}] engines disagree about how much text was drawn (${perEngine.map(([name, m]) => `${name} ${(m.textRatio * 100).toFixed(2)}%`).join(", ")})`);
    }
  }

  if (failures.length > 0) {
    for (const failure of failures) console.error(failure);
    throw new Error(`${failures.length} cross-browser export check(s) failed`);
  }
  console.log(`All export checks passed on ${collected.map(([name]) => name).join(", ")}.`);
}

main().catch(error => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
