import { chromium, firefox, webkit, type BrowserType } from "playwright";
import { renderExportSvg } from "../src/exportImage.ts";

const labels = {
  questionLabel: "Question:", variantLabel: "Variant:", codeLabel: "This is the code:",
  resultLabel: "... and this is the result:", viewCodeLabel: "View", viewResultLabel: "View result",
  matchesLabel: "matches the expected result!", doesNotMatchLabel: "does not match the expected result!",
  generatedByLabel: "Generated by SQL Validator at test time",
};
const columns = Array.from({ length: 48 }, (_, index) => index % 2 ? "label" : `column_${index}`);
const data = Array.from({ length: 90 }, (_, row) => columns.map((_, column) => column === 0 ? null : column === 1 ? new Uint8Array([0, row, 255]) : `<value ${row}-${column}>`));
const rendered = renderExportSvg({ labels, query: {
  question: { category: { display_number: "82" }, display_sequence: "D", description: "Render a large escaped result consistently across browser engines" },
  code: "SELECT p.name, COUNT(o.id) AS orders FROM Person p LEFT JOIN Orders o ON o.person_id = p.id WHERE p.name < 'Z' GROUP BY p.name ORDER BY p.name;",
  result: { columns, data }, isCorrect: true,
} });

async function run(type: BrowserType, name: string): Promise<void> {
  let browser;
  try {
    browser = await type.launch({ headless: true, args: ["--no-sandbox"] });
  } catch (error) {
    console.warn(`[${name}] skipped: browser binary unavailable (${String(error).split("\n")[0]})`);
    return;
  }
  try {
    const page = await browser.newPage();
    await page.setContent(rendered.svg);
    const result = await page.evaluate(async ({ svg, width, height }) => {
      const image = new Image();
      image.src = URL.createObjectURL(new Blob([svg], { type: "image/svg+xml" }));
      await new Promise<void>((resolve, reject) => { image.onload = () => resolve(); image.onerror = () => reject(new Error("image decode failed")); });
      const source = document.createElement("canvas"); source.width = width * 2; source.height = height * 2;
      source.getContext("2d")!.drawImage(image, 0, 0, source.width, source.height);
      const output = document.createElement("canvas"); output.width = width; output.height = height;
      output.getContext("2d")!.drawImage(source, 0, 0, source.width, source.height, 0, 0, width, height);
      const dataUrl = output.toDataURL("image/png");
      return { width: output.width, height: output.height, signature: dataUrl.slice(0, 30), hasForeignObject: document.documentElement.innerHTML.includes("foreignObject") };
    }, rendered);
    if (result.width !== rendered.width || result.height !== rendered.height) throw new Error("PNG dimensions changed during rasterization");
    if (result.hasForeignObject) throw new Error("export contains foreignObject");
    if (!result.signature.startsWith("data:image/png;base64,")) throw new Error("PNG encoding failed");
    console.log(`[${name}] passed (${result.width}x${result.height})`);
  } finally {
    await browser.close();
  }
}

await run(chromium, "chromium");
await run(firefox, "firefox");
await run(webkit, "webkit");
