// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from "vitest";
import { downloadExportPng, renderExportSvg } from "./exportImage";

const labels = {
  questionLabel: "Question",
  variantLabel: "Variant",
  codeLabel: "Code",
  resultLabel: "Result",
  viewCodeLabel: "View",
  viewResultLabel: "View result",
  matchesLabel: "Matches",
  doesNotMatchLabel: "Does not match",
  generatedByLabel: "Generated by test",
};

const result = (columns: string[], data: (number | string | Uint8Array | null)[][]) => ({ columns, data });

afterEach(() => {
  vi.restoreAllMocks();
  vi.unstubAllGlobals();
});

describe("renderExportSvg", () => {
  it("renders escaped query content and matching status without foreignObject", () => {
    const rendered = renderExportSvg({
      labels,
      query: {
        question: { category: { display_number: "1<&" }, display_sequence: "A", description: "Find <all> & rows" },
        code: "SELECT \"<&\"\nFROM people",
        result: result(["id", "name"], [[1, "Alice & Bob"]]),
        isCorrect: true,
        mode: "sql",
      },
    });

    expect(rendered.svg).not.toContain("foreignObject");
    expect(rendered.svg).toContain("Find &lt;all&gt; &amp; rows");
    expect(rendered.svg).toContain("&quot;&lt;&amp;&quot;");
    expect(rendered.svg).toContain("matches</tspan>");
    expect(rendered.width).toBe(1200);
    expect(rendered.height).toBeGreaterThan(260);
  });

  it("handles large tables, duplicate labels, NULL and binary values deterministically", () => {
    const columns = Array.from({ length: 80 }, (_, index) => index % 2 ? "label" : `column_${index}`);
    const data = Array.from({ length: 120 }, (_, row) => columns.map((_, column) =>
      column === 0 ? null : column === 1 ? new Uint8Array([0, row, 255]) : `${row}-${column}`));
    const rendered = renderExportSvg({ labels, view: { view: { name: "wide_view", query: "SELECT * FROM wide_view" }, result: result(columns, data) } });

    expect(rendered.svg).toContain("NULL");
    expect(rendered.svg).toContain("00 00 ff");
    expect(rendered.svg.match(/label/g)?.length).toBeGreaterThan(1);
    expect(rendered.height).toBeGreaterThan(3000);
    expect(rendered.svg.length).toBeGreaterThan(100_000);
  });

  it("wraps long multiline code and supports a non-matching query", () => {
    const rendered = renderExportSvg({ labels, query: {
      question: { category: { display_number: "2" }, display_sequence: "B", description: "description" },
      code: `${"x".repeat(400)}\nsecond line`,
      result: result(["value"], [[null]]),
      isCorrect: false,
    } });

    expect(rendered.svg).toContain("Does not match");
    expect(rendered.svg).toContain("SECOND");
    expect((rendered.svg.match(/<text /g) ?? []).length).toBeGreaterThan(10);
  });

  it("rejects ambiguous or empty payloads", () => {
    expect(() => renderExportSvg({ labels })).toThrow(/Exactly one/);
    expect(() => renderExportSvg({ labels, query: {} as never, view: {} as never })).toThrow(/Exactly one/);
  });
});

describe("downloadExportPng", () => {
  const rendered = { svg: "<svg xmlns='http://www.w3.org/2000/svg' width='10' height='10'/>", width: 10, height: 10 };

  it("rasterizes, downloads, and revokes the temporary SVG URL", async () => {
    const urls = { created: [] as string[], revoked: [] as string[] };
    vi.stubGlobal("URL", {
      createObjectURL: vi.fn(() => { const url = `blob:${urls.created.length}`; urls.created.push(url); return url; }),
      revokeObjectURL: vi.fn((url: string) => urls.revoked.push(url)),
    });
    class MockImage {
      onload?: () => void;
      onerror?: () => void;
      set src(_value: string) { queueMicrotask(() => this.onload?.()); }
    }
    vi.stubGlobal("Image", MockImage);
    const click = vi.fn();
    const canvas = { width: 0, height: 0, getContext: vi.fn(() => ({ drawImage: vi.fn() })), toBlob: vi.fn((cb: (blob: Blob) => void) => cb(new Blob(["png"]))) };
    const createElement = vi.spyOn(document, "createElement").mockImplementation((tag: string) => tag === "canvas" ? canvas as unknown as HTMLElement : ({ click, set href(value: string) { void value; }, set download(value: string) { void value; } } as unknown as HTMLElement));

    await downloadExportPng(rendered, "export.png");
    expect(canvas.width).toBe(10);
    expect(canvas.height).toBe(10);
    expect(click).toHaveBeenCalledOnce();
    expect(urls.revoked).toEqual(["blob:0"]);
    createElement.mockRestore();
  });

  it("rejects image decode failures and still revokes the temporary URL", async () => {
    const revoke = vi.fn();
    vi.stubGlobal("URL", { createObjectURL: vi.fn(() => "blob:failed"), revokeObjectURL: revoke });
    class FailedImage {
      onload?: () => void;
      onerror?: () => void;
      set src(_value: string) { queueMicrotask(() => this.onerror?.()); }
    }
    vi.stubGlobal("Image", FailedImage);

    await expect(downloadExportPng(rendered, "export.png")).rejects.toThrow("Unable to rasterize");
    expect(revoke).toHaveBeenCalledWith("blob:failed");
  });
});
