// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from "vitest";
import { downloadExportPng, rasterizeExportPng, rasterScale, renderExportSvg, type ExportImageLabels, type RenderedExportSvg } from "./exportImage";

const labels: ExportImageLabels = {
  questionLabel: "Question",
  variantLabel: "Variant",
  codeLabel: "Code",
  resultLabel: "Result",
  viewCodeLabel: "View",
  viewResultLabel: "View result",
  matchesLabel: "MATCHES",
  doesNotMatchLabel: "Does not match",
  truncatedLabel: ({ rows, totalRows, columns, totalColumns }) => `Showing ${rows}/${totalRows} rows, ${columns}/${totalColumns} columns`,
  generatedByLabel: "Generated by test",
};

const result = (columns: string[], data: (number | string | Uint8Array | null)[][]) => ({ columns, data });
const grid = (columnCount: number, rowCount: number, cell = (row: number, column: number) => `${row}-${column}`) => result(
  Array.from({ length: columnCount }, (_, index) => `column_${index}`),
  Array.from({ length: rowCount }, (_, row) => Array.from({ length: columnCount }, (_, column) => cell(row, column))),
);

/** Right/bottom edge of every drawn box, so overflow past the canvas is visible. */
function boxBounds(svg: string): { right: number; bottom: number; left: number; top: number } {
  const rects = [...svg.matchAll(/<rect x="([\d.-]+)" y="([\d.-]+)" width="([\d.]+)" height="([\d.]+)"/g)]
    .map(([, x, y, width, height]) => ({ x: Number(x), y: Number(y), width: Number(width), height: Number(height) }));
  expect(rects.length).toBeGreaterThan(0);
  return {
    left: Math.min(...rects.map(r => r.x)),
    top: Math.min(...rects.map(r => r.y)),
    right: Math.max(...rects.map(r => r.x + r.width)),
    bottom: Math.max(...rects.map(r => r.y + r.height)),
  };
}

afterEach(() => {
  vi.restoreAllMocks();
  vi.unstubAllGlobals();
});

describe("renderExportSvg", () => {
  it("renders escaped query content and the localized matching status without foreignObject", () => {
    const rendered = renderExportSvg({
      labels,
      query: {
        question: { category: { display_number: "1<&" }, display_sequence: "A", description: "Find <all> & rows" },
        code: "SELECT \"<&\"\nFROM people",
        result: result(["id", "name"], [[1, "Alice & Bob"]]),
        isCorrect: true,
        mode: "sql",
      },
    });

    expect(rendered.svg).not.toContain("foreignObject");
    expect(rendered.svg).toContain("Find &lt;all&gt; &amp; rows");
    expect(rendered.svg).toContain("&quot;&lt;&amp;&quot;");
    expect(rendered.svg).toContain("MATCHES</tspan>");
    expect(rendered.width).toBe(1200);
    expect(rendered.height).toBeGreaterThan(260);
  });

  it("keeps a wide table inside the canvas by growing it and dropping the columns that still do not fit", () => {
    const rendered = renderExportSvg({ labels, view: { view: { name: "wide_view", query: "SELECT * FROM wide_view" }, result: grid(48, 6) } });
    const bounds = boxBounds(rendered.svg);

    // The bug this guards: cell boxes used to run to x=3696 on a 1200px canvas.
    expect(rendered.width).toBeGreaterThan(1200);
    expect(rendered.width).toBeLessThanOrEqual(2560);
    expect(bounds.left).toBeGreaterThanOrEqual(0);
    expect(bounds.top).toBeGreaterThanOrEqual(0);
    expect(bounds.right).toBeLessThanOrEqual(rendered.width);
    expect(bounds.bottom).toBeLessThanOrEqual(rendered.height);
    expect(rendered.svg).toContain("columns");
    expect(rendered.svg).toMatch(/Showing 6\/6 rows, \d+\/48 columns/);
  });

  it("stays within the canvas for a narrow table that needs no truncation", () => {
    const rendered = renderExportSvg({ labels, view: { view: { name: "v", query: "SELECT * FROM v" }, result: grid(3, 4) } });
    const bounds = boxBounds(rendered.svg);

    expect(rendered.width).toBe(1200);
    expect(bounds.right).toBeLessThanOrEqual(1200);
    expect(bounds.left).toBeGreaterThanOrEqual(64);
    expect(rendered.svg).not.toContain("Showing");
  });

  it("handles duplicate labels, NULL and binary values, and drops rows that exceed the rasterizable height", () => {
    const columns = Array.from({ length: 80 }, (_, index) => index % 2 ? "label" : `column_${index}`);
    const data = Array.from({ length: 400 }, (_, row) => columns.map((_, column) =>
      column === 0 ? null : column === 1 ? new Uint8Array([0, row, 255]) : `${row}-${column}`));
    const rendered = renderExportSvg({ labels, view: { view: { name: "wide_view", query: "SELECT * FROM wide_view" }, result: result(columns, data) } });

    expect(rendered.svg).toContain("NULL");
    expect(rendered.svg).toContain("00 00 ff");
    expect(rendered.svg.match(/label/g)?.length).toBeGreaterThan(1);
    expect(rendered.svg.length).toBeGreaterThan(100_000);
    // A canvas past the engine limits rasterizes to a blank image, so the
    // layout has to fit inside them rather than rely on the capture step.
    expect(rendered.height).toBeLessThanOrEqual(8192);
    expect(rendered.width * rendered.height).toBeLessThanOrEqual(16_777_216);
    expect(boxBounds(rendered.svg).right).toBeLessThanOrEqual(rendered.width);
    expect(rendered.svg).toMatch(/Showing \d+\/400 rows, \d+\/80 columns/);
  });

  it("truncates an outlying cell value instead of widening its column past the canvas", () => {
    const rendered = renderExportSvg({ labels, view: { view: { name: "v", query: "SELECT * FROM v" }, result: result(["note"], [["x".repeat(4000)]]) } });

    expect(rendered.width).toBeLessThanOrEqual(2560);
    expect(boxBounds(rendered.svg).right).toBeLessThanOrEqual(rendered.width);
    expect(rendered.svg).toContain("…");
  });

  it("wraps long multiline code and supports a non-matching query", () => {
    const rendered = renderExportSvg({ labels, query: {
      question: { category: { display_number: "2" }, display_sequence: "B", description: "description" },
      code: `${"x".repeat(400)}\nsecond line`,
      result: result(["value"], [[null]]),
      isCorrect: false,
    } });

    expect(rendered.svg).toContain("Does not match");
    expect(rendered.svg).toContain("SECOND");
    expect((rendered.svg.match(/<text /g) ?? []).length).toBeGreaterThan(10);
    expect(boxBounds(rendered.svg).right).toBeLessThanOrEqual(rendered.width);
  });

  it("caps a pathologically long query instead of producing an unrasterizable canvas", () => {
    const rendered = renderExportSvg({ labels, query: {
      question: { category: { display_number: "3" }, display_sequence: "C", description: "long" },
      code: Array.from({ length: 5000 }, (_, index) => `-- line ${index}`).join("\n"),
      result: result(["value"], [[1]]),
      isCorrect: true,
    } });

    expect(rendered.height).toBeLessThanOrEqual(8192);
    expect(rendered.width * rendered.height).toBeLessThanOrEqual(16_777_216);
  });

  it("leaves relational algebra unformatted rather than running it through the SQL formatter", () => {
    const rendered = renderExportSvg({ labels, query: {
      question: { category: { display_number: "4" }, display_sequence: "D", description: "ra" },
      code: "π[id](select from Person)",
      result: result(["id"], [[1]]),
      isCorrect: true,
      mode: "ra",
    } });

    expect(rendered.svg).toContain("π[id](select from Person)");
    expect(rendered.svg).not.toContain("SELECT");
  });

  it("wraps a long heading on word boundaries rather than mid-word", () => {
    const rendered = renderExportSvg({ labels, query: {
      question: { category: { display_number: "5" }, display_sequence: "E", description: "List every person together with how many orders they placed in the last year" },
      code: "SELECT 1",
      result: result(["id"], [[1]]),
      isCorrect: true,
    } });
    const heading = [...rendered.svg.matchAll(/font-size="32px"[^>]*>([^<]*)</g)].map(match => match[1]);

    expect(heading.length).toBeGreaterThan(1);
    expect(heading.join(" ").replace(/\s+/g, " ").trim()).toBe("List every person together with how many orders they placed in the last year");
    for (const line of heading) expect(line.trim()).toBe(line);
  });

  it("rejects ambiguous or empty payloads", () => {
    expect(() => renderExportSvg({ labels })).toThrow(/Exactly one/);
    expect(() => renderExportSvg({ labels, query: {} as never, view: {} as never })).toThrow(/Exactly one/);
  });
});

describe("rasterScale", () => {
  it("supersamples 2x when the raster fits and backs off when it would not", () => {
    expect(rasterScale(1200, 400)).toBe(2);
    expect(rasterScale(2560, 6553)).toBeLessThan(2);
    expect(rasterScale(2560, 6553)).toBeGreaterThanOrEqual(1);
    expect(rasterScale(2560, 6553) * 2560 * rasterScale(2560, 6553) * 6553).toBeLessThanOrEqual(16_777_216 + 1);
  });

  it("never asks for a canvas larger than an engine allows, at any size the layout can produce", () => {
    for (const [width, height] of [[1200, 320], [1200, 8192], [2560, 6553], [2560, 4096]] as const) {
      const scale = rasterScale(width, height);
      expect(scale).toBeGreaterThanOrEqual(1);
      expect(Math.round(width * scale)).toBeLessThanOrEqual(8192);
      expect(Math.round(height * scale)).toBeLessThanOrEqual(8192);
      expect(Math.round(width * scale) * Math.round(height * scale)).toBeLessThanOrEqual(16_777_216 + 8192);
    }
  });
});

describe("rasterizeExportPng", () => {
  const rendered: RenderedExportSvg = { svg: "<svg xmlns='http://www.w3.org/2000/svg' width='10' height='10'/>", width: 10, height: 10 };

  const stubCanvas = () => {
    const canvases: { width: number; height: number }[] = [];
    const click = vi.fn();
    vi.spyOn(document, "createElement").mockImplementation((tag: string) => {
      if (tag !== "canvas") return { click, set href(value: string) { void value; }, set download(value: string) { void value; } } as unknown as HTMLElement;
      const canvas = { width: 0, height: 0, getContext: vi.fn(() => ({ drawImage: vi.fn(), fillRect: vi.fn(), fillStyle: "" })), toBlob: vi.fn((cb: (blob: Blob) => void) => cb(new Blob(["png"]))) };
      canvases.push(canvas);
      return canvas as unknown as HTMLElement;
    });
    return { canvases, click };
  };

  it("supersamples then downscales to the requested size and revokes the temporary SVG URL", async () => {
    const urls = { created: [] as string[], revoked: [] as string[] };
    vi.stubGlobal("URL", {
      createObjectURL: vi.fn(() => { const url = `blob:${urls.created.length}`; urls.created.push(url); return url; }),
      revokeObjectURL: vi.fn((url: string) => urls.revoked.push(url)),
    });
    class MockImage {
      onload?: () => void;
      onerror?: () => void;
      set src(_value: string) { queueMicrotask(() => this.onload?.()); }
    }
    vi.stubGlobal("Image", MockImage);
    const { canvases } = stubCanvas();

    const blob = await rasterizeExportPng(rendered);
    expect(blob.size).toBeGreaterThan(0);
    expect(canvases.map(canvas => [canvas.width, canvas.height])).toEqual([[20, 20], [10, 10]]);
    expect(urls.revoked).toEqual(["blob:0"]);
  });

  it("downloads the rasterized blob", async () => {
    vi.stubGlobal("URL", { createObjectURL: vi.fn(() => "blob:x"), revokeObjectURL: vi.fn() });
    class MockImage {
      onload?: () => void;
      set src(_value: string) { queueMicrotask(() => this.onload?.()); }
    }
    vi.stubGlobal("Image", MockImage);
    const { click } = stubCanvas();

    await downloadExportPng(rendered, "export.png");
    expect(click).toHaveBeenCalledOnce();
  });

  it("rejects image decode failures and still revokes the temporary URL", async () => {
    const revoke = vi.fn();
    vi.stubGlobal("URL", { createObjectURL: vi.fn(() => "blob:failed"), revokeObjectURL: revoke });
    class FailedImage {
      onload?: () => void;
      onerror?: () => void;
      set src(_value: string) { queueMicrotask(() => this.onerror?.()); }
    }
    vi.stubGlobal("Image", FailedImage);

    await expect(rasterizeExportPng(rendered)).rejects.toThrow("Unable to rasterize");
    expect(revoke).toHaveBeenCalledWith("blob:failed");
  });
});
