name: Eslint CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check line endings (LF)
      run: bash scripts/check-line-endings.sh
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npx eslint --max-warnings 0 .
